config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "superheros#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :superheros do
    resources :bookings, only: [:new, :create ]
    resources :reviews, only: [:new, :create]
  end

  patch "bookings/:id/accept", to: "bookings#accept", as: "accept"
  patch "bookings/:id/decline", to: "bookings#decline", as: "decline"


  get "/users/account", to: "pages#account"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :superhero
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :superhero
end

app/models/superhero.rb
class Superhero < ApplicationRecord
  CATEGORY = ["Mangeur de bananes", "Tireur d'exception", "Homme en slip", "Créature chelou", "Développeur full stack"]

  include PgSearch::Model
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, presence: true, allow_blank: false

  pg_search_scope :search_by_name_and_team,
  against: [ :name, :team ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :superheros, dependent: :destroy
  has_many :bookings
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @superhero = Superhero.find(params[:superhero_id])
    @booking = Booking.new
    @booking.superhero = @superhero

    # if @booking.save!
    # redirect_to list_path(@list)
    # else
    # render 'lists/show', status: :unprocessable_entity
    # end
  end

  def create
    @superhero = Superhero.find(params[:superhero_id])
    @booking = Booking.new(booking_params)
    @booking.accepted = nil
    @booking.superhero = @superhero
    @booking.user = current_user
    booking_save
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update!(accepted: true)
    redirect_to users_account_path, status: :see_other
    flash[:alert] = "You accepted the reservation of #{@booking.user.email} made on #{@booking.superhero.name}"
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.update!(accepted: false)
    redirect_to users_account_path, status: :see_other
    flash[:alert] = "You declined the reservation of #{@booking.user.email} made on #{@booking.superhero.name}"
  end
end

private

def booking_save
  if @booking.save!
    redirect_to superhero_path(@superhero)
    flash[:alert] = "Vous avez bien reservé #{@superhero.name}"
  else
    render 'superheros/show', status: :unprocessable_entity
  end
end

def booking_params
  params.require(:booking).permit(:checkin, :checkout)
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def account
    @user = current_user
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_superhero

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(reviews_params)
    @review.superhero = @superhero
    @review.user = current_user
    if @review.save!
      redirect_to superhero_path(@superhero)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_superhero
    @superhero = Superhero.find(params[:superhero_id])
  end

  def reviews_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/superheros_controller.rb
class SuperherosController < ApplicationController
  before_action :set_superhero, only: [:show, :edit, :update, :destroy]

  def index
    @superheros = Superhero.all
    if params[:query]
      @superheros = @superheros.search_by_name_and_team(params[:query])
    end
  end

  def new
    @superhero = Superhero.new
  end

  def show
    @booking = Booking.new
    @review = Review.new
  end

  def create
    @superhero = Superhero.new(superhero_params)
    @superhero.user = current_user
    if @superhero.save!
      redirect_to superhero_path(@superhero)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @superhero.update(superhero_params)
    redirect_to superhero_path(superhero_params)
  end

  def destroy
    @superhero.destroy
    redirect_to superheros_path, status: :see_other
    flash[:alert] = "Vous avez bien supprimé #{@superhero.name}"
  end

  private

  def set_superhero
    @superhero = Superhero.find(params[:id])
  end

  def superhero_params
    params.require(:superhero).permit(:name, :team, :image_url, :address, :coverimage, :category, :booktitle, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
<%= simple_form_for [@superhero, @booking] do |f| %>
  <%= f.input :checkin %>
  <%= f.input :checkout %>
  <%= f.submit %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsVoughtAgency</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container-fluid">
    <div class="row">
      <div class="col-2">
        <%= render "shared/navbar" %>
      </div>
      <div class="col-10">
        <%= yield %>
        <%= render "shared/flashes" %>
        <%= render "shared/footer" %>

      </div>
    </div>
  </body>
</html>

app/views/pages/account.html.erb
<div class="container mt-5">
  <h3>Hello, <%= @user.email %></h3>

   <%= link_to new_superhero_path,  class:"btn btn-primary mt-3"  do %>
    <i class="fa-solid fa-plus"></i> Add a new superhero
  <% end %>


  <h1 class="mt-3">Mes superheros</h1>

<ul class="d-flex flex-row flex-wrap gap-3">
    <div class="row justify-content-between">
     <% @user.superheros.each do |superhero| %>
        <li class="border rounded sh-card col-2 mx-2 my-4">
        <%= link_to superhero_path(superhero) do %>
          <img class="banner_superhero rounded-top" src=<%= superhero.image_url %> alt=<%= superhero.name %>>
          <div class="position-relative">
            <img class="logo_marvel rounded-circle" src="https://tse3.mm.bing.net/th?id=OIP.bxbNzr2ihmPnVrGzBOZiJgHaHa&pid=Api&P=0&h=180" alt="">

            <div class="info_superhero">
              <h1><%= superhero.name %></h1>
              <p><%= superhero.category %></p>

              <div class= "d-flex align-items-center sh-geoloc">
                <i class="fa-solid fa-location-pin"></i>
                <span class="ms-2"><%= superhero.address %></span>
              </div>
              <div class="edition-founctions">
              <%= link_to edit_superhero_path(superhero) do %>
                  <span class="span-edit btn btn-outline-light mt-3">Edit</span>
                <% end %>
                <%= link_to superhero_path(superhero),
                            class:"trash-btn btn btn-outline-danger mt-3",
                            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}  do %>
                <i class="fa-solid fa-trash"  id="delete-ico"></i> Supprimer
                <% end %>
              </div>
            </div>

          </div>
        <% end %>
        </li>
      <% end %>
    </div>
  </ul>

  <div class="row">
    <div class="col-6">
    <h1 >Mes bookings de superheros</h1>
    <ul>
      <% @user.bookings.each do |booking| %>
        <% if booking.accepted == nil %>
        <li>
          <%= booking.superhero.name %> is booked
        </li>
        <li>
          From <%= booking.checkin %> to <%= booking.checkout %>
        </li>
          <%= link_to "accept booking", accept_path(booking), data: {turbo_method: :patch}, class:"btn btn-outline-success"%>
          <%= link_to "decline booking", decline_path(booking), data: {turbo_method: :patch}, class:"btn btn-outline-warning"%>
        <% elsif booking.accepted %>
          <li>
          <%= booking.superhero.name %> is booked
          </li>
          <li>
          From <%= booking.checkin %> to <%= booking.checkout %>
        </li>
          <%= link_to "decline booking", decline_path(booking), data: {turbo_method: :patch}, class:"btn btn-outline-warning"%>
        <% end %>
      <% end %>
      <%  %>
    </ul>
    </div>
    <div class="col-6">
    <h1>Les bookings de mes superheros</h1>
    <ul>

        <% @user.superheros.each do |superhero| %>
          <% if superhero.bookings.any? %>
          <li>
            <%= superhero.name %> is booked
          </li>
          <% end  %>
          <% superhero.bookings.each do |booking| %>
            <% if booking.accepted %>
            <li>
              From <%= booking.checkin %> to <%= booking.checkout %>
              by <%= booking.user.email %>
            </li>
            <% else %>
            but it's still pending...
            <% end %>
          <% end %>
        <% end %>

    </ul>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/new.html.erb
<%= simple_form_for [@superhero, @review] do |f| %>
  <%= f.input :comment %>
  <%= f.input :rating %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-sh d-flex align-items-center justify-content-center">
  <ul class="list-group list-group-horizontal">
    <li class="list-group-item">
        © Vought Intl.
    </li>
    <li class="list-group-item">
Privacy policy
    </li>
    <li class="list-group-item">
Terms of Service
    </li>
    <li class="list-group-item">
Site Data Collection
    </li>

  </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon col-2 justify-content-center">
  <div class="p-2 d-flex align-items-start flex-column" id="sidebar-global">

    <div class="sidebar-logo my-4">
     <%= link_to root_path, class: " py-5 border-bottom" do %>
            <%= cl_image_tag("n9xfsyr3qprnjpwav77i") %>
          <% end %>
    </div>




    <div class="icone">
      <div class="collapse navbar-collapse p-2" id="navbarSupportedContent">

        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <div class="sidebar-menu">
              <li class="nav-item active">
                <p>MENU</p>
                <%= link_to root_path, class: "nav-link" do %>
                  <i class="fa-solid fa-house"></i> <span class="px-2 py-3">Accueil</span>
                <% end  %>
              </li>

              <li class="nav-item">
                <%= link_to users_account_path, class: "nav-link" do%>
                  <i class="fa-regular fa-circle-user"></i> <span class="px-2 py-3">Compte</span>
                <% end  %>
              </li>

              <li class="nav-item active">
                <%= link_to users_account_path, class: "nav-link" do %>
                  <i class="fa-regular fa-bell"></i> <span class="px-2 py-3">Notification</span>
                <% end %>
              </li>

              <li class="nav-item active">
                <div class="add-a-sh">
                    <%= link_to new_superhero_path,  class:"btn btn-outline-primary mt-5 px-4"  do %>
                        <i class="fa-solid fa-plus"></i> Add a superhero
                      <% end %>
                </div>
              </li>
            </div>
      </div>

          <div class="pt-5 border-top mt-auto p-2 ">
            <div class="profil-area d-flex gap-2">
            <%= cl_image_tag("crgi6hu1imbn3kczzelq", class: "avatar rounded-circle") %>
              <div class="profil-area-infos">
                <p><%= current_user.email %></p>
                <p>Owner of <%= current_user.superheros.length %> SH</p>
              </div>
            </div>
              <%=link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link logout" do%>
                <i class="fa-solid fa-arrow-right-from-bracket  pt-4"></i> Log out
              <% end  %>

          </div>
          <% else %>
            <div class="sidebar-menu">
              <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              </li>
              </div>
            </div>
          <% end %>
        </ul>

    </div>
</div>
</div>

app/views/superheros/_form.html.erb
<%= simple_form_for [@superhero] do |f| %>
  <%= f.input :name %>
  <%= f.input :team %>
  <%= f.input :category, collection:Superhero::CATEGORY %>
  <%= f.input :booktitle %>
  <%= f.input :description %>
  <%= f.input :coverimage %>
  <%= f.input :image_url %>
  <%= f.input :address %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/superheros/edit.html.erb
<div class="container">
   <%= render "form", superhero: @superhero %>
</div>

app/views/superheros/index.html.erb
  <div class="row justify-content-center search-area">
    <h1 class="text-center w-100 mt-5">Looking for a <span class="bolder">Superhero</span> ?</h1>
    <div class="col-sm-8">
      <%= form_with url: superheros_path, method: :get, class: "d-flex search-form" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control p-3",
              placeholder: "Type a keyword"
          %>
          <i class="fa-solid fa-magnifying-glass search-loupe"></i>
        <%= submit_tag "Search", name: "", class: "btn btn-primary d-none" %>
      <% end %>
    </div>
    </div>
<div class="container">
  <div class="btn btn-outline-light px-4 py-2 sh-filtres"><i class="fa-solid fa-sliders"></i> Filtres</div>

  <ul class="d-flex flex-row flex-wrap gap-3" data-controller="fakelazy" data-action="scroll@window->fakelazy#magicreveal">
    <div class="row justify-content-between">
      <% @superheros.each do |superhero| %>
        <li class="border rounded sh-card col-2 mx-2 my-4"  data-fakelazy-target="reveal">
        <%= link_to superhero_path(superhero) do %>
          <div class="reflect-card"></div>
          <img class="banner_superhero rounded-top" src=<%= superhero.image_url %> alt=<%= superhero.name %>>
          <div class="position-relative">
            <img class="logo_marvel rounded-circle" src="https://tse3.mm.bing.net/th?id=OIP.bxbNzr2ihmPnVrGzBOZiJgHaHa&pid=Api&P=0&h=180" alt="">

            <div class="info_superhero">
              <h1><%= superhero.name %></h1>
              <p><%= superhero.category %></p>

              <div class= "d-flex align-items-center sh-geoloc">
                <i class="fa-solid fa-location-pin"></i>
                <span class="ms-2"><%= superhero.address %></span>
              </div>

            </div>

          </div>
        <% end %>
        </li>
      <% end %>
    </div>
  </ul>


</div>

app/views/superheros/new.html.erb
<div class="container">
   <%= render "form", superhero: @superhero %>
</div>

app/views/superheros/show.html.erb
<div class="hero-show-sh d-flex flex-column justify-content-end py-5" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.5)), url('<%= @superhero.coverimage %>');">
  <div class="container">
    <h1><%= @superhero.name %></h1>
    <h3>// <%= @superhero.category %></h3>
    <p><%= @superhero.team %></p>
  </div>
</div>


<div class="container">
  <div class="row mt-5">
    <div class="col-8">

      <% if @superhero.user == current_user %>
        <%= link_to edit_superhero_path(@superhero), class:"btn btn-outline-primary" do %>
          <span>Edit</span>
        <% end %>

        <%= link_to superhero_path(@superhero),
                    class:"btn btn-outline-primary ms-2",
                    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}  do %>
          <span>Delete</span>
        <% end %>
      <% end%>

      <h1 class="mt-2"><%= @superhero.booktitle %></h1>
      <p><%= @superhero.description %></p>
      <img src="<%= @superhero.image_url %>" alt="superhero" style="max-width:80%;">

      <% if @superhero.reviews.any? %>
        <hr>
        <h2>Commentaires</h2>
        <ul class="list-group">
          <% @superhero.reviews.each do |review| %>
            <li class="list-group-item"><%= review.comment %> by <%= review.user.email %></li>
          <% end %>
        </ul>
      <% end %>
      <hr>

      <h2>Faire un retour sur la préstation de <%= @superhero.name %></h2>
      <%= simple_form_for [@superhero, @review] do |f| %>
      <%= f.input :comment %>
      <%= f.input :rating %>
      <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col-4">
      <div class="booking-area p-4 border rounded" data-controller="totalprice">
        <div class="price border-bottom pb-3"><span data-totalprice-target="price">132</span> € par jour</div>
        <%= simple_form_for [@superhero, @booking] do |f| %>
          <%= f.input :checkin,
             label: "Jour de début de mission",
             as: :string,
             input_html: { data: { controller: "datepicker", totalprice_target: "checkin", action: "change->totalprice#calcul"} } %>
          <%= f.input :checkout,
              label: "Jour de fin de mission",
              as: :string,
              input_html: { data: { controller: "datepicker", totalprice_target: "checkout" , action: "change->totalprice#calcul"}  } %>
          <p class="text-center">Aucun montant ne vous sera débité pour le moment</p>
          <%= f.button :submit, class: "btn btn-primary w-100 py-3", label: "Réserver ce super héro" %>
        <% end %>
        <div class="total-price border-top mt-3 pt-3 text-end" data-totalprice-target="totalPrice"></div>
      </div>
    </div>
  </div>

</div>